In [1]:
2 + 2

4

In [2]:
4.567 % 1

0.5670000000000002

In [3]:
# The math module

In [4]:
from math import pi

In [5]:
pi

3.141592653589793

In [6]:
import math

In [7]:
math.sqrt(25)

5.0

In [8]:
math.sin(pi/2)

1.0

In [9]:
math.cos(pi/2)

6.123233995736766e-17

In [10]:
math.exp(2)

7.38905609893065

In [11]:
math.log(2)

0.6931471805599453

In [12]:
math.e

2.718281828459045

In [13]:
# Python random

In [14]:
import random

In [15]:
random.randint(0,10) # 0 and 10 also possible

1

In [16]:
# uniform means no subrange is more likely than any other

In [17]:
random.uniform(3.5, 4.5)

3.7088351679138074

In [18]:
# Collections

In [19]:
months = ['Jan', 'Feb', 'Mar', 'Aprial', 'May', 'August']

In [20]:
months

['Jan', 'Feb', 'Mar', 'Aprial', 'May', 'August']

In [21]:
months[-1]

'August'

In [22]:
months[0:2]

['Jan', 'Feb']

In [23]:
len(months)

6

In [24]:
months[2:]

['Mar', 'Aprial', 'May', 'August']

In [25]:
month_year = [x + ' 2021' for x in months]

In [26]:
month_year

['Jan 2021', 'Feb 2021', 'Mar 2021', 'Aprial 2021', 'May 2021', 'August 2021']

In [51]:
# convert range in to a list
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
list(range(0,20,3))

[0, 3, 6, 9, 12, 15, 18]

In [29]:
# zip function takes in two iterables and create pairs with corresponding entries
z = zip([1,2,3],["a","c","c"])
# z is a class convert it to a list
print(list(z))

[(1, 'a'), (2, 'c'), (3, 'c')]


In [30]:
# Generators
# Create iterable that do not store all the values in memory

In [31]:
# define function ending with yield instead of return
# generators can return many values where functions can only return once

In [32]:
def count():
    x = 0
    while True:
        x = x + 1
        yield x # this returns a generater object which can be iterated over

In [33]:
for x in count():
    if x < 4:
        print(x)
    else:
        break

1
2
3


In [34]:
# we can create generator comprehension py wrapping using parentheses insead of breackets
result = (x*x for x in range(0,10))
print(result)

<generator object <genexpr> at 0x7fb7d30b35f0>


In [35]:
# when the generator is finite you can convert it to a list using list() function
print(list(result))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [36]:
# Tuples are the default collection in python
numbers = 0,1,2,3,4,5,6,7
print(numbers)

(0, 1, 2, 3, 4, 5, 6, 7)


In [37]:
# If you just return two or more values from a function, by default it will be interpretered as a tuple
def tupe_return():
    return 1,2
print(tupe_return())

(1, 2)


In [38]:
# Sets
# every entry must be distinct
# turning a list in to a set is a quick way to guarantee it has no duplicates
# the set function convert, iterable in to a set
dups = [1,2,2,3,3,3,4,5,5,5,5,6,7,7]
print(set(dups))
print(list(set(dups)))

{1, 2, 3, 4, 5, 6, 7}
[1, 2, 3, 4, 5, 6, 7]


In [39]:
# sets are equal if they has same entries regardless of order
set([1,2,3]) == {3,2,1}

True

In [40]:
# NumPy
import numpy as np

In [41]:
# to create a numpy array, just pass a iterable to np.array function
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [42]:
# use arange function
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# third agument is value to count by, which can be a float
np.arange(0,4,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [44]:
# Dictionaries
dog = {
    "name" : "Melba",
    "age" : 2
}
print(dog["name"])

Melba


In [45]:
# get all values from dictionary as a key value pair using items()
print(list(dog.items()))

[('name', 'Melba'), ('age', 2)]


In [46]:
# Useful collection functions

In [47]:
# sum function adds up a iterable
sum((1,2,3))

6

In [48]:
# min and max returns smallest and larget values from iterable

In [49]:
# sorted returns a list that sorted copy of a iterable
sorted([5,2,3,8,2,4])

[2, 2, 3, 4, 5, 8]

In [50]:
# reverse function returns a iterable which has the order reveresed, this is not a list
print(reversed([1,2,3,4,5,6]))

In [52]:
# Functions

In [53]:
# define function that accept variable number of arguments as a tuple

In [55]:
def variable_fun(*args):
    for arg in args:
        print(arg)

In [56]:
variable_fun(5,6,7,8)

5
6
7
8


In [58]:
# * operator can be used to convert a list in to a arguments for a function
argument_list = ['a','b','c','d']

In [60]:
variable_fun(*argument_list)

a
b
c
d


In [61]:
# optional keyword arguments

In [62]:
def birthday(name='friend', age=None):
    s = "Happy birthday, %s" % name
    if age:
        s += ", you're %d years old" % age
    return s + "!"

In [63]:
birthday(name='Ruchira', age=33)

"Happy birthday, Ruchira, you're 33 years old!"

In [64]:
# you can pass a dictionary keyword argument using ** instead of passing seperate arguments
args = {'name': 'Ruchira Munidasa', 'age': 35}

In [65]:
birthday(**args)

"Happy birthday, Ruchira Munidasa, you're 35 years old!"

In [66]:
# Functions as data

In [67]:
# you can pass functions as variables

In [70]:
def square(x):
    return x*x

In [71]:
list(map(square, range(4)))

[0, 1, 4, 9]

In [72]:
# functions can return functions

In [77]:
def make_power_function(power):
    def power_function(x): # this is a closure cause it remebers the outside variables
        return x ** power
    return power_function

In [74]:
cube_function = make_power_function(3)

In [76]:
cube_function(2)

8

In [78]:
# Lambdas: Anonymous functions

In [81]:
(lambda x: x + 2)(7)

9

In [82]:
# lambda should be used in situations such as functions that return or take other functions

In [83]:
# applying functions to numpy arrays

In [84]:
# to apply custom function to every entry in numpy use np.vectorize function

In [85]:
def cube_function(x):
    return x ** 3

In [86]:
import numpy as np

np_cube_function = np.vectorize(cube_function)

In [87]:
np_cube_function(np.arange(0,4))

array([ 0,  1,  8, 27])